kind: Pod 
apiVersion: v1
metadata:
  name: web
spec:
  volumes:
  - name: html
    hostPath:
      path: /webdata
  containers:
  - name: nginx
    image: nginx:1.14
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html 
