apiVersion: v1
kind: Pod
metadata:
  name: web-nfs
spec:
  containers:
  - image: quay.io/centos/centos:stream9  # Fixed typo here (centoss -> centos)
    name: nginx-container
    command: ['sh', '-c', 'echo "hello" && sleep 3600']
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  volumes:
  - name: html
    nfs:
      server: 192.168.10.15
      path: /nas/k8s
