apiVersion: v1
kind: Service
metadata:
  name: webapp-nodeport-svc
spec:
  type: NodePort
  clusterIP: 10.96.10.10   	# 생략 가능(생략하면 IP 자동할당)
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000   			# 생략 가능(생략하면 Port 자동할당)
