apiVersion: v1
kind: Service
metadata:
  name: webapp-loadbalancer-svc
spec:
  type: LoadBalancer
  clusterIP: 10.96.10.10
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000
