apiVersion: v1
kind: Pod
metadata:
  name: mysnata
spec:
  containers:
  - name: mysnata
    image: nginx:1.15
    volumeMounts:
    - name: mysnata
      mountPath: /usr/share/nginx/html
      readOnly: true
  volumes:
  - name: myindex 
    configmap:
      name: myindex