apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mainui-rs
spec:
  replicas: 2
  selector: 
    matchLabels:
      name: apache
      app: main
      rel: stable
  template:
    metadata:
      name: mainui-pod
      labels:
        name: apache
        app: main
        rel: stable
    spec:
      containers:
      - image:  httpd:2.2
        name: mainui-container 
        ports:
        - containerPort: 80
          protocol: TCP
