apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  # ClusterRoleBinding 이름 설정
  name: app-manager-binding
subjects:
- kind: User
  name: app-manager
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: app-manager-clusterrole
  apiGroup: rbac.authorization.k8s.io

